### PR TITLE
Fix ValueError when checking 'from . import a' statement

### PR DESCRIPTION
**Pull request by mhthies**
When this kind of statement is found in file under check, which is located in a top-level package, the check crashed with a "ValueError: attempted relative import beyond top-level package".

This was caused by an excess dot when trying to import the module. It was only triggered, when the imported module has not been imported by the flake8 interpreter in any other way yet, because the broken import would be skipped in this case.

This PR also adapts the tests to check for this error condition.

### CODE REVIEW

**Comment by atollk** [comment]
Thanks for the contribution. I don't quite see how the added line in the test covers this issue. There should be a line somewhere in the form of `from . import x` as you described to verify that the change doesn't actually crash any more, or am I missing something?

**Comment by mhthies** [comment]
The exception is raised from within the `imports_submodule()` function when calling it with the following arguments:
```python
imports_submodule(filename="my_package/b.py", level=1, from_="", import_="a")
```
(and the module `my_package.a` has not been imported before).

Cause for the exception: With this set of arguments, `imports_submodule()` tries to invoke `importlib.import_module("..a", my_package)`, which would be an import above the top-level package.

In practice, the function is called with these parameters when an `from . import a` statement is encountered in second-level module file (e.g. "my_package/b.py").

Still, I thought it would be sufficient to test the correct behaviour of the `imports_submodule()` method with these parameters, instead of adding an end-to-end test. Additionally, I wouldn't know where to put it, since this faulty behaviour is not limited to a single warning.

The new test requires that the `test_imports_submodule.py` is imported is located one directory directory below the working directory and the python path. This is usually the case when running `pytest` in the project root directory.

**Comment by atollk** [comment]
I understand that thought process.

The issue I am having right now is that I cannot reproduce the error with your given test. If I insert the new test line in my project from the master branch, it still passes. After checking, I am actually surprised by the error in the first place because the exception that you describe ("attempted relative import beyond top-level package") usually is an `ImportError`, not a `ValueError`. And the former is already covered by a `try`-`except`. 

Do you have an example project that reproduced the error?

**Comment by mhthies** [comment]
The original repository, where we encountered the error, is internal, unfortunately.

The issue can be reproduced with the following minimal test project:

```txt
./
└── ./my_project
    ├── __init__.py
    ├── a.py
    └── b.py
```

a.py:
```python
from . import b
```

The following works:
```bash
flake8 .
```

The following fails:
```bash
flake8 my_project
```

**Comment by atollk** [comment]
Maybe it's a version issue then? This is the output when I run your command on the current `master` revision.

```
❯ pytest ./tests/test_imports_submodule.py
=============================================================================================================================================== test session starts ================================================================================================================================================
platform linux -- Python 3.12.4, pytest-7.4.4, pluggy-1.5.0
rootdir: /home/andreas/Projects/git/flake8-import-restrictions
plugins: flake8-path-1.5.0
collected 5 items                                                                                                                                                                                                                                                                                                  

tests/test_imports_submodule.py .....                                                                                                                                                                                                                                                                        [100%]

================================================================================================================================================ 5 passed in 0.01s =================================================================================================================================================
```

Could you post your output? I'll try to do some research on what might cause the error to appear.

**Comment by atollk** [comment]
I ran the test on several versions and it fails on Python 3.8. Indeed, this seems to be supported by the changelog of 3.9: https://docs.python.org/3/whatsnew/3.9.html#other-language-changes

It feels a bit odd to add this now, considering 3.8 is at it's end of life in a few months, but I guess we can still add the fix if you need it.

Can you confirm that you are using Python 3.8?

**Comment by mhthies** [comment]
Yes, we are still using Python 3.8.

However, if I understand correctly, the issue in `imports_submodule()` is still present with Python >= 3.9. Only my test fails to detect it, since the changed exception type is caught inside the function. (This may result in a false-negative result, which is not checked by my test.) I'll try to improve the test to correctly report the issue on newer Python versions.

**Comment by atollk** [comment]
Yes, the false negatives would probably be there in all versions of Python. They just don't crash everything.

I'd appreciate if you could make the test detect the false negative, not the crash. It'd probably be easier for you than me since you're more involved with the specific setup in the first place. 
In the meantime, I added a fix for the crash to the main branch (just converting it to a false negative by catching the `ValueError`). If you're somehow dependent on this being packaged for your project as soon as possible, I could release an intermediate version until this proper fix is merged.

**Comment by mhthies** [comment]
I've added a new test to check the relative import behaviour including the false-negative result of imports_submodule() when using a relative import with empty `from_` parameter. The test needs to temporarily modify the working directory and sys.path to achive the correct conditions to make the faulty behaviour observable.

**Comment by atollk** [comment]
Looks good to me :) thanks

**Pull request merged**
